apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-app
  description: Python ile yazılmış Serverless Ödeme Servisi
  annotations:
    github.com/project-slug: 'mert/mert-k3slab-infra'
    backstage.io/kubernetes-id: payment-app 
  tags:
    - python
    - serverless
    - knative
    - finance
spec:
  type: service
  lifecycle: experimental
  owner: devops-team
  system: payment-system
  providesApis: []
