elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
  replicas: 1
  javaOpts: "-Xms512m -Xmx512m"

kibana:
  image: docker.elastic.co/kibana/kibana:7.17.10
  port: 30601 

logstash:
  image: docker.elastic.co/logstash/logstash:7.17.10

filebeat:
  image: docker.elastic.co/beats/filebeat:7.17.10

generator:
  image: alpine:latest
